rbac:
  create: true
  role: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argocd-namespace-role
    rules:
    - apiGroups: [""]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["argoproj.io"]
      resources: ["applications"]
      verbs: ["*"]
  roleRef: |
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-namespace-role
  roleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argocd-namespace-role-binding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: argocd-namespace-role
    subjects:
    - kind: ServiceAccount
      name: argocd-server


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-controller
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-controller-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
roleRef:
  kind: Role
  name: argocd-application-controller
  apiGroup: rbac.authorization.k8s.io

