apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---

apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
metadata:
  name: app-test-1-deploy
  namespace: app-test-1
spec:
  replicas: 10
  selector:
    matchLabels: 
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: nginx
        ports:
        - name: web
          containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
# --- Everything above this comment are the same as a deployment ---
    canary: # A new field for configurable Canary options
      maxSurge: "60%"
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - analysis:
          templates:
          - templateName: canary-check
      - pause:
          duration: 30 #seconds
      - setWeight: 50
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  type: LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-1-ingress
  namespace: app-test-1
spec:
  rules:
  - host: "app-test-1.kube-demo-1.clcreative.home"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-1-svc
            port:
              number: 80
              
---
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: canary-check
  namespace: app-test-1
spec:
  metrics:
  - name: webmetric
    successCondition: "result.series >= 'f1' && result.limit >= '30'"
    provider:
      web:
        url: "http://ergast.com/api/f1/2004/1/results.json"
        jsonPath: "{$.MRData}"
